In [1]:
# Pandas is used for data manipulation
import pandas as pd# Read in data and display first 5 rows
featurespd = pd.read_excel('atributosshap_en.xlsx')
#featurespd=featurespd.drop(featurespd.columns[49], axis=1)
featurespd.head(5)

,Area,Average elevation,Minimum elevation,Maximum elevation,Gauge elevation,Slope,Catchment order,Average daily precipitation,Average daily minimum temp.,Average daily maximum temp.,...,Soil carbon,Soil density,Soil depth,Soil texture,Centroid longitude,Centroid latitude,Distance from the coast,Longitude,Latitude,Biome
0,243410.279,178.97,44.65,564.03,44.65,3.14,7,5.64,21.61,30.48,...,16.099,1.335,25.456,1,-68.028,-8.989,1407.55,-64.384,-6.541,1
1,76898.617,222.97,80.40,2892.44,80.40,4.72,6,8.88,21.83,28.60,...,34.458,1.256,17.609,2,-66.695,2.016,1009.09,-66.851,1.215,1
2,24018.785,151.47,80.86,952.20,80.86,2.81,4,8.52,22.18,29.67,...,30.098,1.219,20.530,3,-68.936,1.573,1009.70,-67.595,1.074,1
3,127540.913,184.31,74.32,2892.44,74.32,3.71,6,8.86,22.00,29.13,...,34.490,1.235,18.612,3,-67.305,1.734,1095.42,-67.313,0.372,1
4,41762.638,206.08,85.09,615.36,85.09,2.30,5,7.79,21.91,28.80,...,34.200,1.248,20.859,3,-70.894,1.201,964.52,-69.126,0.477,1

In [2]:
# Pandas is used for data manipulation
import pandas as pd# Read in data and display first 5 rows
assinaturas = pd.read_excel('assinaturas4_en2.xlsx')
#assinaturas=assinaturas.drop(assinaturas.columns[166], axis=1)
assinaturas.head(5)

,Mean,Median,CV,Annual mean,Summer mean,Winter mean,January mean flow,February mean flow,March mean flow,April mean flow,...,Annual Maximum 30,Annual Maximum 60,Annual Maximum 90,25th Percentile,10th Percentile,5th Percentile,Annual Minimum 1,Annual Minimum 3,95th Percentile,90th Percentile
0,2.246598,1.958990,0.710198,820.532541,301.352715,78.504094,2.851524,3.812693,4.277156,4.391897,...,4.335217,4.272602,4.190658,3.990546,4.371414,4.517997,0.399855,0.400712,0.389777,0.433747
1,5.603617,5.184328,0.558521,2046.627738,250.018848,836.857260,2.777654,2.679665,2.730307,3.990075,...,10.504984,10.069261,9.606907,8.168142,10.133704,11.168153,1.112284,1.130327,1.163949,1.694501
2,6.690720,6.124165,0.484416,2443.673863,356.897288,891.927200,3.704536,3.923545,4.340492,6.040811,...,12.038821,11.355388,10.769113,9.180754,11.423671,12.423473,1.576785,1.636112,2.124857,2.840715
3,5.718842,5.276860,0.497289,2088.711779,298.245208,801.193765,3.278185,3.238349,3.389938,4.541160,...,10.226817,9.793426,9.346311,8.095271,9.834361,10.628229,1.472966,1.496748,1.717152,2.257425
4,5.060316,4.668613,0.546841,1848.196020,211.418299,715.461109,2.247108,2.075443,2.581409,4.405773,...,9.559175,8.879782,8.419035,7.098921,8.919723,9.915354,0.821239,0.856222,1.092270,1.620889

In [3]:
from sklearn.dummy import DummyRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVR
from sklearn.neural_network import MLPRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from catboost import CatBoostRegressor
from sklearn.metrics import mean_absolute_error, median_absolute_error, roc_auc_score, r2_score, explained_variance_score
from lightgbm import LGBMRegressor

modelnames = [
 'LGBMRegressor(n_estimators = 500)', 
 'KNeighborsRegressor()',
 'LinearRegression()', 
#'LogisticRegression()', 
 'SVR()',
 #'MLPRegressor(hidden_layer_sizes = (16, 16))',
 #'DecisionTreeRegressor()', 
 'GradientBoostingRegressor(n_estimators = 500)',
 'XGBRegressor(n_estimators = 500, max_depth=20)',
 'CatBoostRegressor(silent = True, n_estimators = 500)',
 'RandomForestRegressor(n_estimators = 500)',
]

metricnames = [
 'mean_absolute_error', 
# 'median_absolute_error',
 'r2_score',
# 'explained_variance_score'
]

columnnames = [
  'iter',  
  'assinaturaId',
 'assinatura', 
 'modelo', 
 'fold',
 'mean_absolute_error', 
 #'median_absolute_error',
 'r2_score',
 #'explained_variance_score'
]

metrics = pd.DataFrame(index = modelnames, columns = columnnames)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
import numpy as np
resultados = []

for k in range(0,5):
    for i in range(0,len(assinaturas.columns)):
        print(assinaturas.columns[i])
        y = np.array(assinaturas[assinaturas.columns[i]])# Remove the labels from the features
        X = np.array(featurespd)

        X = X[~np.isnan(y)]
        y = y[~np.isnan(y)]

        for modelname in modelnames:
            #try:
                kf = KFold(n_splits=10,shuffle=True)
                kf.get_n_splits(X)
                for j, (train, test) in enumerate(kf.split(X)):
                  model = eval(modelname)
                  linha = []
                  pred_test = model.fit(X[train], y[train]).predict(X[test])
                  metrics.loc[modelname, 'assinaturaId'] = i
                  metrics.loc[modelname, 'assinatura'] = assinaturas.columns[i]
                  linha.append(k)
                  linha.append(i)
                  linha.append(assinaturas.columns[i])
                  linha.append(modelname)
                  linha.append(j)
                  for metricname in metricnames:
                    val = eval(f'{metricname}(y[test], pred_test)')
                    linha.append(val)
                    #print(val)
                    #metrics.loc[modelname, metricname] = eval(f'{metricname}(y_test, pred_test)')
                  resultados.append((linha))
            #except:
            #    print(modelname)
        rf = pd.DataFrame(resultados, columns=columnnames)
        rf.to_csv('results.csv',sep=";")  
    rf = pd.DataFrame(resultados, columns=columnnames)
    rf.to_csv('results.csv',sep=";")  
    
rf = pd.DataFrame(resultados, columns=columnnames)